### ISSUE TITLE
Links broken to Sutta Central Khandhaka

### ISSUE THREAD

**Issue by Kaccana-Bhikkhu** [thesunshade/citation-helper#32]
Thank you very much for creating such a useful tool. I'm planning to use links to sutta.readingfaithfully.org in a Dhamma project, and noticed a minor but annoying bug.

On the live https://sutta.readingfaithfully.org site, Kd links to Sutta Central are missing a '/', which breaks the link. For example the page:

https://sutta.readingfaithfully.org/?q=Kd-1.14 contains the link:

https://suttacentral.netpli-tv-kd1/en/sujato (broken)

adding '/' yields:

https://suttacentral.net/pli-tv-kd1/en/sujato (works, although it doesn't yet link to section 14)

Hopefully this can be fixed the next time you update the website.

All good wishes,
 - Kaccāna Bhikkhu

**Comment by thesunshade** [comment]
> https://suttacentral.netpli-tv-kd1/en/sujato (broken)

Thank you so much! It should be fixed now.

> (works, although it doesn't yet link to section 14)

I don't really have any plans to support that. If by section 14 you mean the 14th item in the table of contents, that's tricky. The way SC represents that in the url is `#pli-tv-kd1:23.1.0`. So I'd have to make a table to make correspondents between the sections in the TOC and the real SC segments. And then I'd have to have a way in the interface so that the user would be able to indicate that the number they were using was for the TOC section and not the SC section.

I'm open to ideas, but I'm not sure it's worth it.

That said, I'd love to hear how you are using the tool. Being able to link to the tool itself with a particular citation was kind of an afterthought. It's useful for linking to suttas since there can be so many alternative translations. But for the Vinaya there is just the one.

**Comment by thesunshade** [comment]
Ah, then I believe you are the venerable one I know from Abhayagiri. I was at your samanera ordination.

Please drop me a line when you have a chance. info@readingfaithfully.org
